services:
  webgl:
    build:
      context: .
      dockerfile: Dockerfile.webgl
      args:
        EMSDK_VERSION: 5.0.7
        SDL_VERSION: 3.4.12
        SDL_IMAGE_VERSION: 3.4.4
        SDL_TTF_VERSION: 3.2.2
        SDL_MIXER_VERSION: 3.2.4
    volumes:
      - ./build:/app/build
    command: sh -c "cp -r /tmp/dist/* /app/build/ && chmod -R 777 /app/build/"
  linux:
    build:
      context: .
      dockerfile: Dockerfile.linux
      args:
        SDL_VERSION: 3.4.12
        SDL_IMAGE_VERSION: 3.4.4
        SDL_TTF_VERSION: 3.2.2
        SDL_MIXER_VERSION: 3.2.4
    volumes:
      - ./build:/app/build
    command: sh -c "cp -r /tmp/dist/* /app/build/ && chmod -R 777 /app/build/"
