name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  EMSDK_VERSION: 4.0.18

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Cache Emscripten
        id: cache-emscripten
        uses: actions/cache@v4
        with:
          path: ./emsdk
          key: ${{ runner.os }}-emsdk-${{ env.EMSDK_VERSION }}

      - name: Install Emscripten
        if: steps.cache-emscripten.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd ./emsdk
          ./emsdk install ${{ env.EMSDK_VERSION }}
          ./emsdk activate ${{ env.EMSDK_VERSION }}

      - name: Download Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Build WebGL
        run: |
          source ./emsdk/emsdk_env.sh
          mkdir -p build/web
          emcc -std=c++17 -Os -o build/web/index.html src/*.cpp -Ifonts -Iimages -Iinclude -Isrc \
              -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='["png"]' -s USE_SDL_TTF=2 -s USE_SDL_MIXER=2 \
              --shell-file templates/web-minimal.html
          gzip -k build/web/index.wasm

      - name: Push to Itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          ./butler push ./build/web scottdoxey/pong-demo:html5

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          path: ./build
          overwrite: true
