name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: HandcrankEngine/install-sdl-packages@3dd8adf2ce1e6698313aecb05a2f8fa59be27b8c # v0.4.1
        with:
          BUILD_SDL_FOR_EMSCRIPTEN: true
          SDL_VERSION: 2.32.10
          SDL_IMAGE_VERSION: 2.8.12
          SDL_TTF_VERSION: 2.24.0
          SDL_MIXER_VERSION: 2.8.2

      - name: Build WebGL
        run: |
          mkdir -p build/web
          emcc -std=c++17 -Os -o build/web/index.html src/*.cpp -Ifonts -Iimages -Iinclude -Isrc \
            -I"${SDL_PATH}/include/SDL2" -L"${SDL_PATH}/lib" \
            -I"${SDL_IMAGE_PATH}/include/SDL2" -L"${SDL_IMAGE_PATH}/lib" \
            -I"${SDL_TTF_PATH}/include/SDL2" -L"${SDL_TTF_PATH}/lib" \
            -I"${SDL_MIXER_PATH}/include/SDL2" -L"${SDL_MIXER_PATH}/lib" \
            -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer \
            -s USE_FREETYPE=1 -s USE_HARFBUZZ=1 \
            -s MAX_WEBGL_VERSION=2 \
            --shell-file templates/web-minimal.html
          gzip -k build/web/index.wasm

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: ./build
          overwrite: true
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: build/

      - name: Download Butler
        run: |
          curl -L -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Push to Itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          ./butler push ./build/web scottdoxey/pong-demo:html5
